AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] 
BATCH_SIZE: 32  
INCLUDE_TOP: False
EPOCHS: 150
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.00001 

# AUGMENTATION: True
# IMAGE_SIZE: [224, 224, 3]
# BATCH_SIZE: 32
# INCLUDE_TOP: False
# EPOCHS: 25 
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.0001
# CLASS_WEIGHTS: {0: 1, 1: 2.5}  
# LOSS: focal_loss() 
