AUGMENTATION: True  
IMAGE_SIZE: [224, 224, 3]  
BATCH_SIZE: 32  
INCLUDE_TOP: False  
EPOCHS: 50    
CLASSES: 2  
WEIGHTS: imagenet  
LEARNING_RATE: 0.00005 


# AUGMENTATION: True
# IMAGE_SIZE: [224, 224, 3]
# BATCH_SIZE: 32
# INCLUDE_TOP: False
# EPOCHS: 25 
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.0001
# CLASS_WEIGHTS: {0: 1, 1: 2.5}  
# LOSS: focal_loss() 
